import { test, expect } from '@playwright/test';
import { TenantsPage } from '../pages/tenants_page';
import { AdminLoginPage } from '../pages/AdminLoginPage';



  test(' Confirmation message on submission', async ({ page }) => {
    await page.goto('https://hub-surgia-test.dentacartscloud.net/register');
    await page.getByRole('textbox', { name: 'Enter clinic/hospital name' }).click();
    await page.getByRole('textbox', { name: 'Enter clinic/hospital name' }).fill('dgdfgdfgdfgdfg');
    await page.locator('select[name="type"]').selectOption('HOSPITAL');
    await page.locator('select[name="city_id"]').selectOption('2');
    await page.getByRole('textbox', { name: 'First name' }).click();
    await page.getByRole('textbox', { name: 'First name' }).fill('dddd');
    await page.getByRole('textbox', { name: 'Last name' }).click();
    await page.getByRole('textbox', { name: 'Last name' }).fill('dddd');
    await page.getByRole('textbox', { name: 'Enter contact email' }).click();
    await page.getByRole('textbox', { name: 'Enter contact email' }).fill('ddddddddd@dd.dd');
    await page.getByRole('textbox', { name: 'Enter without country code' }).click();
    await page.getByRole('textbox', { name: 'Enter without country code' }).fill('510125415');
    await page.getByRole('textbox', { name: 'Enter without country code' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await expect(page.getByText('Request was submitted')).toBeVisible();
  });
  test('Clinic type options', async ({ page }) => {
    await page.goto('https://hub-surgia-test.dentacartscloud.net/register');
    await page.locator('select[name="type"]').selectOption('HOSPITAL');
    await expect(page.locator('select[name="type"]')).toBeVisible();
    await page.locator('select[name="type"]').selectOption('POLY_CLINIC');
    await expect(page.locator('select[name="type"]')).toBeVisible();
  });
  test('required fields are mandatory', async ({ page }) => {
    await page.goto('https://hub-surgia-test.dentacartscloud.net/register');
    await page.getByRole('button', { name: 'Submit' }).click();
    await expect(page.locator('div').filter({ hasText: /^Clinic\/Hospital Name \*Required$/ }).getByRole('paragraph')).toBeVisible();
    await expect(page.locator('div').filter({ hasText: /^Clinic\/Hospital Type \*Select typeHospitalPoly ClinicOtherRequired$/ }).getByRole('paragraph')).toBeVisible();
    await expect(page.locator('form div').filter({ hasText: 'City *Select cityAl-BahahAl-' }).getByRole('paragraph')).toBeVisible();
    await expect(page.locator('div').filter({ hasText: /^First Name \*Required$/ }).getByRole('paragraph')).toBeVisible();
    await expect(page.locator('div').filter({ hasText: /^Contact Person Email \*Required$/ }).getByRole('paragraph')).toBeVisible();
    await expect(page.locator('div').filter({ hasText: /^Enter phone number \*🇸🇦Required$/ }).getByRole('paragraph')).toBeVisible();
  });
  test(' confirmation email is sent', async ({ page }) => {
    await page.goto('https://hub-surgia-test.dentacartscloud.net/register');
    await page.getByRole('textbox', { name: 'Enter clinic/hospital name' }).click();
    await page.getByRole('textbox', { name: 'Enter clinic/hospital name' }).fill('dgdfgdfgdfgdfg');
    await page.locator('select[name="type"]').selectOption('HOSPITAL');
    await page.locator('select[name="city_id"]').selectOption('2');
    await page.getByRole('textbox', { name: 'First name' }).click();
    await page.getByRole('textbox', { name: 'First name' }).fill('dddd');
    await page.getByRole('textbox', { name: 'Last name' }).click();
    await page.getByRole('textbox', { name: 'Last name' }).fill('dddd');
    await page.getByRole('textbox', { name: 'Enter contact email' }).click();
    await page.getByRole('textbox', { name: 'Enter contact email' }).fill('ddddddddd@dd.dd');
    await page.getByRole('textbox', { name: 'Enter without country code' }).click();
    await page.getByRole('textbox', { name: 'Enter without country code' }).fill('510125415');
    await page.getByRole('textbox', { name: 'Enter without country code' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await expect(page.getByText('Request was submitted')).toBeVisible();
 });
 test('login with valid credentials', async ({ page }) => {
  await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('new@mailna.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
});
test('login with valid credentials and verify redirect to dashboard', async ({ page }) => {
  await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('new@mailna.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await expect(page).toHaveURL('https://hub-surgia-test.dentacartscloud.net/');
});
test('Account activation after profile completion', async ({ page }) => {
  await page.goto('https://admin-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('menna.mohamed@dentacarts.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.locator('div').filter({ hasText: 'Nice to see you again Email' }).nth(1).click();
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('link', { name: 'Tenants' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('row', { name: '354 dgdfgdfgdfgdfg Hospital' }).locator('span').nth(4).click();
  await page.getByRole('button', { name: 'Activate now' }).click();
  await page.getByRole('button', { name: 'Next' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Enter branch name' }).click();
  await page.getByRole('textbox', { name: 'Enter branch name' }).fill('rrrr');
  await page.locator('select[name="city"]').selectOption('3');
  await page.locator('select[name="district"]').selectOption('22');
  await page.getByRole('textbox', { name: 'Enter address' }).click();
  await page.getByRole('textbox', { name: 'Enter address' }).fill('rrrrrrrrrrrrrrrrrrrrr');
  await page.getByRole('textbox', { name: 'Enter first name' }).click();
  await page.getByRole('textbox', { name: 'Enter first name' }).fill('r');
  await page.getByRole('textbox', { name: 'Enter last name' }).click();
  await page.getByRole('textbox', { name: 'Enter last name' }).fill('r');
  await page.getByRole('textbox', { name: 'Enter without country code' }).click();
  await page.getByRole('textbox', { name: 'Enter without country code' }).fill('510147458');
  await page.getByRole('button', { name: 'Activate' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('Failed to activate Tenant')).toBeVisible();
});
test('Redirect based on role after login', async ({ page }) => {
  await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('demoooop@mailna.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Users' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Catalog' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Purchase Requests' })).toBeVisible();
});
test('Save valid changes to price and quantities', async ({ page }) => {
  await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('new@mailna.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('link', { name: 'Catalog' }).click();
  await page.getByRole('button', { name: 'Start Icon Add to PR' }).click();
  await page.getByRole('button', { name: 'Cart' }).click();
  await page.getByRole('button', { name: 'Increase' }).first().click();
  await page.getByRole('button', { name: 'Increase' }).first().click();
  await expect(page.getByText('Item quantity updated')).toBeVisible();
});
test('Add to PR with valid variant & quantity', async ({ page }) => {
  await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('new@mailna.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('link', { name: 'Catalog' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('Auto');
  await page.getByRole('button', { name: 'Start Icon Add to PR' }).click();
  await page.getByRole('button', { name: 'Black' }).click();
  await page.getByRole('button', { name: '1 g' }).click();
  await page.getByRole('button', { name: 'Increase' }).click();
  await page.getByRole('button', { name: 'Start Icon Add to PR' }).nth(2).click();
  await expect(page.getByText('Item quantity updated')).toBeVisible();
  await page.getByRole('button', { name: 'white' }).click();
  await page.getByRole('button', { name: 'g' }).click();
  await page.getByRole('button', { name: 'Increase' }).click();
  await expect(page.getByRole('button', { name: 'Start Icon Add to PR' }).nth(2)).toBeVisible();
  await page.getByRole('button', { name: 'Start Icon Add to PR' }).nth(2).click();
  await expect(page.getByText('Item quantity updated')).toBeVisible();
  });
  test('Assign product with custom name/price', async ({ page }) => {
    await page.goto('https://admin-surgia-test.dentacartscloud.net/login');
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByRole('textbox', { name: 'Email Address' }).fill('menna.mohamed@dentacarts.com');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('123456');
    await page.getByRole('button', { name: 'Sign In', exact: true }).click();
    await page.getByRole('link', { name: 'Tenants' }).click();
    await page.getByRole('row', { name: '733 SmithamLLCvoXUUKTp' }).getByRole('button').click();
    await page.getByRole('button', { name: 'Start Icon Assign product' }).click();
    await page.getByRole('cell', { name: 'checked 6892025820777' }).getByRole('img').click();
    await page.getByRole('button', { name: 'Next →' }).click();
    await page.locator('.bg-white > .flex.items-center.justify-between').click();
    await page.getByRole('button', { name: 'Next →' }).click();
    await page.getByText('AutomationParent ProductCompleted').click();
    await page.getByRole('textbox', { name: 'Customer product name' }).click();
    await page.getByRole('textbox', { name: 'Customer product name' }).fill('qqqqqq');
    await page.getByPlaceholder('Maximum Quantity').click();
    await page.getByPlaceholder('Maximum Quantity').fill('910');
    await page.getByRole('button', { name: 'Save Changes' }).click();
    await expect(page.getByText('Product configuration saved')).toBeVisible();
    await page.getByRole('button', { name: 'Finish' }).click();
    await expect(page.getByRole('region', { name: 'Notifications alt+T' }).getByRole('listitem')).toBeVisible();
  });
  test('product list updates dynamically', async ({ page }) => {
    await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByRole('textbox', { name: 'Email Address' }).fill('new@mailna.co');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('123456');
    await page.getByRole('button', { name: 'Sign In', exact: true }).click();
    await page.getByRole('link', { name: 'Catalog' }).click();
    await page.getByRole('textbox', { name: 'Search' }).click();
    await page.getByRole('textbox', { name: 'Search' }).fill('Auto');
    await page.getByRole('button', { name: 'Start Icon Add to PR' }).click();
    await page.getByRole('button', { name: 'Black' }).click();
    await page.getByRole('button', { name: '1 g' }).click();
    await page.getByRole('button', { name: 'Increase' }).click();
    await page.getByRole('button', { name: 'Start Icon Add to PR' }).nth(2).click();
    await expect(page.getByText('Item quantity updated')).toBeVisible();
});
test('product details page loads', async ({ page }) => {
  await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('new@mailna.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('link', { name: 'Catalog' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('Auto');
  await page.getByRole('button', { name: 'Start Icon Add to PR' }).click();
  await page.getByRole('button', { name: 'Black' }).click();
});
test('View user details (authorized)', async ({ page }) => {
  await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('new@mailna.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('link', { name: 'Users' }).click();
  await expect(page.getByRole('cell', { name: 'ID sort' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'User name sort' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'User details' })).toBeVisible();
  await expect(page.getByText('Roles')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Assigned Branch sort' })).toBeVisible();
});
test('navigate user list pagination', async ({ page }) => {
  await page.goto('https://hub-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('new@mailna.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('link', { name: 'Users' }).click();
  await expect(page.getByRole('cell', { name: 'ID sort' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'User name sort' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'User details' })).toBeVisible();
  await expect(page.getByText('Roles')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Assigned Branch sort' })).toBeVisible();
  await page.getByRole('button', { name: '2' }).click();
  await page.getByRole('button', { name: '3' }).click();
  await expect(page.getByText('User name')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'User details' })).toBeVisible();
});
test('Activate tenant with valid fields', async ({ page }) => {
  await page.goto('https://admin-surgia-test.dentacartscloud.net/login');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('menna.mohamed@dentacarts.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.locator('div').filter({ hasText: 'Nice to see you again Email' }).nth(1).click();
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('link', { name: 'Tenants' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('row', { name: '354 dgdfgdfgdfgdfg Hospital' }).locator('span').nth(4).click();
  await page.getByRole('button', { name: 'Activate now' }).click();
  await page.getByRole('button', { name: 'Next' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Enter branch name' }).click();
  await page.getByRole('textbox', { name: 'Enter branch name' }).fill('rrrr');
  await page.locator('select[name="city"]').selectOption('3');
  await page.locator('select[name="district"]').selectOption('22');
  await page.getByRole('textbox', { name: 'Enter address' }).click();
  await page.getByRole('textbox', { name: 'Enter address' }).fill('rrrrrrrrrrrrrrrrrrrrr');
  await page.getByRole('textbox', { name: 'Enter first name' }).click();
  await page.getByRole('textbox', { name: 'Enter first name' }).fill('r');
  await page.getByRole('textbox', { name: 'Enter last name' }).click();
  await page.getByRole('textbox', { name: 'Enter last name' }).fill('r');
  await page.getByRole('textbox', { name: 'Enter without country code' }).click();
  await page.getByRole('textbox', { name: 'Enter without country code' }).fill('510147458');
  await page.getByRole('button', { name: 'Activate' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('Failed to activate Tenant')).toBeVisible();
});

